include("${config}")
file(MAKE_DIRECTORY "${cache}")
file(LOCK "${cache}/build.lock" GUARD PROCESS TIMEOUT 1800)
set(complete TRUE)
foreach(library avformat avcodec swscale swresample avutil)
    if(NOT EXISTS "${cache}/install/lib/lib${library}.a")
        set(complete FALSE)
    endif()
endforeach()
if(complete AND EXISTS "${cache}/complete" AND EXISTS "${cache}/install/include/libavcodec/avcodec.h")
    return()
endif()
file(MAKE_DIRECTORY "${cache}/build")
execute_process(COMMAND ${command} WORKING_DIRECTORY "${cache}/build"
    OUTPUT_FILE "${cache}/build.log" ERROR_FILE "${cache}/build.log" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    file(READ "${cache}/build.log" output)
    string(LENGTH "${output}" length)
    if(length GREATER 6000)
        math(EXPR start "${length} - 6000")
        string(SUBSTRING "${output}" ${start} -1 output)
    endif()
    message(FATAL_ERROR "FFmpeg build failed (${result}). Log: ${cache}/build.log\n${output}")
endif()
file(WRITE "${cache}/complete" "Built successfully\n")
